/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * SYGMA DATABASE STUDIO AI — Pre-built Production Templates
 * Complete Relational Schemes with Foreign Keys, Seed Data, Forms, Dashboards & Reports
 */

import { ApplicationSchema, TableDataStore } from './types.ts';

export interface TemplateDefinition {
  id: string;
  name: string;
  category: string;
  description: string;
  icon: string;
  schema: ApplicationSchema;
  initialData: TableDataStore;
}

// 1. PPCI & Inspeção de Segurança Contra Incêndio (Flagship Sygma Model)
export const fireSafetyTemplate: TemplateDefinition = {
  id: 'template_fire_safety_ppci',
  name: 'Sygma PPCI & Inspeção Predial SCI',
  category: 'Segurança Contra Incêndio & Engenharia',
  description: 'Sistema completo de vistoria e licenciamento de segurança contra incêndio, edificações, hidrantes, extintores, alarmes e não conformidades.',
  icon: 'Flame',
  schema: {
    application: {
      id: 'app_sygma_sci_2026',
      name: 'Sygma PPCI & Inspeção Predial SCI',
      description: 'Gestão de vistorias técnicas, sistemas preventivos e controle de não conformidades conforme normas do Corpo de Bombeiros.',
      version: '1.0.0',
      author: 'SYGMA SMS / UNIVERSYGMA',
      createdAt: '2026-09-25T10:00:00Z',
      updatedAt: '2026-09-25T10:00:00Z',
      category: 'Engenharia de Segurança',
      icon: 'ShieldAlert',
    },
    tables: [
      {
        id: 'tbl_empresas',
        name: 'empresas',
        singularLabel: 'Empresa',
        pluralLabel: 'Empresas',
        description: 'Empresas proprietárias ou administradoras das edificações',
        primaryKeyFieldId: 'fld_emp_id',
        position: { x: 50, y: 80 },
        fields: [
          { id: 'fld_emp_id', name: 'id', label: 'ID Empresa', type: 'uuid', primaryKey: true, isSystem: true },
          { id: 'fld_emp_razao', name: 'razao_social', label: 'Razão Social', type: 'text', validation: { required: true } },
          { id: 'fld_emp_cnpj', name: 'cnpj', label: 'CNPJ', type: 'text', validation: { required: true, unique: true } },
          { id: 'fld_emp_contato', name: 'contato_nome', label: 'Responsável', type: 'text' },
          { id: 'fld_emp_email', name: 'email', label: 'E-mail Comercial', type: 'email' },
          { id: 'fld_emp_telefone', name: 'telefone', label: 'Telefone', type: 'phone' },
        ],
      },
      {
        id: 'tbl_edificacoes',
        name: 'edificacoes',
        singularLabel: 'Edificação',
        pluralLabel: 'Edificações',
        description: 'Edifícios residenciais, comerciais, industriais ou hospitalares',
        primaryKeyFieldId: 'fld_edf_id',
        position: { x: 380, y: 80 },
        fields: [
          { id: 'fld_edf_id', name: 'id', label: 'ID Edificação', type: 'uuid', primaryKey: true, isSystem: true },
          { id: 'fld_edf_empresa_id', name: 'empresa_id', label: 'Empresa', type: 'uuid', validation: { required: true } },
          { id: 'fld_edf_nome', name: 'nome_edificio', label: 'Nome do Edifício', type: 'text', validation: { required: true } },
          { id: 'fld_edf_endereco', name: 'endereco', label: 'Logradouro / Número', type: 'text' },
          { id: 'fld_edf_cidade', name: 'cidade', label: 'Município', type: 'text' },
          { id: 'fld_edf_area', name: 'area_construida_m2', label: 'Área Construída (m²)', type: 'decimal' },
          { id: 'fld_edf_altura', name: 'altura_metros', label: 'Altura (m)', type: 'decimal' },
          { id: 'fld_edf_pavimentos', name: 'pavimentos', label: 'Nº Pavimentos', type: 'number' },
          {
            id: 'fld_edf_ocupacao',
            name: 'tipo_ocupacao',
            label: 'Ocupação',
            type: 'text',
            validation: { options: ['Residencial Multifamiliar', 'Comercial / Escritórios', 'Shopping Center', 'Hospitalar / Saúde', 'Indústria / Logística'] }
          },
          {
            id: 'fld_edf_grau_risco',
            name: 'grau_risco',
            label: 'Grau de Risco',
            type: 'text',
            validation: { options: ['Baixo', 'Médio', 'Alto', 'Especial'] }
          },
        ],
      },
      {
        id: 'tbl_inspecoes',
        name: 'inspecoes',
        singularLabel: 'Inspeção',
        pluralLabel: 'Inspeções',
        description: 'Vistorias técnicas periódicas de segurança contra incêndio',
        primaryKeyFieldId: 'fld_insp_id',
        position: { x: 740, y: 80 },
        fields: [
          { id: 'fld_insp_id', name: 'id', label: 'ID Inspeção', type: 'uuid', primaryKey: true, isSystem: true },
          { id: 'fld_insp_edificacao_id', name: 'edificacao_id', label: 'Edificação', type: 'uuid', validation: { required: true } },
          { id: 'fld_insp_data', name: 'data_inspecao', label: 'Data da Inspeção', type: 'date', validation: { required: true } },
          { id: 'fld_insp_inspetor', name: 'inspetor_responsavel', label: 'Engenheiro / Inspetor', type: 'text', validation: { required: true } },
          { id: 'fld_insp_crea', name: 'registro_crea', label: 'CREA / CAU', type: 'text' },
          {
            id: 'fld_insp_status',
            name: 'status_parecer',
            label: 'Parecer Técnico',
            type: 'text',
            validation: { options: ['Aprovado', 'Aprovado com Ressalvas', 'Reprovado', 'Em Andamento'] }
          },
          { id: 'fld_insp_validade_alvara', name: 'validade_avcb', label: 'Validade AVCB / CLCB', type: 'date' },
          { id: 'fld_insp_obs', name: 'observacoes_gerais', label: 'Observações Técnicas', type: 'text' },
        ],
      },
      {
        id: 'tbl_nao_conformidades',
        name: 'nao_conformidades',
        singularLabel: 'Não Conformidade',
        pluralLabel: 'Não Conformidades',
        description: 'Irregularidades e falhas encontradas nos sistemas de combate',
        primaryKeyFieldId: 'fld_nc_id',
        position: { x: 740, y: 420 },
        fields: [
          { id: 'fld_nc_id', name: 'id', label: 'ID Não Conformidade', type: 'uuid', primaryKey: true, isSystem: true },
          { id: 'fld_nc_inspecao_id', name: 'inspecao_id', label: 'Inspeção Vinculada', type: 'uuid', validation: { required: true } },
          {
            id: 'fld_nc_sistema',
            name: 'sistema_afetado',
            label: 'Sistema Afetado',
            type: 'text',
            validation: { options: ['Extintores', 'Hidrantes & Mangotinhos', 'Alarme & Detecção', 'Iluminação de Emergência', 'Portas Corta-Fogo', 'Sprinklers', 'Sinalização'] }
          },
          { id: 'fld_nc_local', name: 'local_pavimento', label: 'Local / Pavimento', type: 'text', validation: { required: true } },
          { id: 'fld_nc_descricao', name: 'descricao_falha', label: 'Descrição da Anomalia', type: 'text', validation: { required: true } },
          {
            id: 'fld_nc_gravidade',
            name: 'gravidade',
            label: 'Gravidade',
            type: 'text',
            validation: { options: ['Leve', 'Média', 'Grave', 'Crítica'] }
          },
          { id: 'fld_nc_prazo', name: 'prazo_adequacao', label: 'Prazo Limite', type: 'date' },
          {
            id: 'fld_nc_situacao',
            name: 'situacao_correcao',
            label: 'Situação',
            type: 'text',
            validation: { options: ['Pendente', 'Em Correção', 'Regularizado', 'Cancelado'] }
          },
        ],
      },
      {
        id: 'tbl_sistemas_instalados',
        name: 'sistemas_instalados',
        singularLabel: 'Sistema Instalado',
        pluralLabel: 'Sistemas Instalados',
        description: 'Inventário dos equipamentos e sistemas de segurança da edificação',
        primaryKeyFieldId: 'fld_sis_id',
        position: { x: 380, y: 420 },
        fields: [
          { id: 'fld_sis_id', name: 'id', label: 'ID Sistema', type: 'uuid', primaryKey: true, isSystem: true },
          { id: 'fld_sis_edificacao_id', name: 'edificacao_id', label: 'Edificação', type: 'uuid', validation: { required: true } },
          { id: 'fld_sis_nome', name: 'nome_sistema', label: 'Nome do Equipamento', type: 'text', validation: { required: true } },
          { id: 'fld_sis_tipo', name: 'tipo', label: 'Tipo / Categoria', type: 'text' },
          { id: 'fld_sis_qtd', name: 'quantidade', label: 'Quantidade Instalada', type: 'number' },
          { id: 'fld_sis_marca', name: 'marca_modelo', label: 'Marca / Fabricante', type: 'text' },
          { id: 'fld_sis_status_op', name: 'status_operacional', label: 'Estado', type: 'text', validation: { options: ['Operacional', 'Em Manutenção', 'Inoperante'] } },
          { id: 'fld_sis_prox_revisao', name: 'data_proxima_revisao', label: 'Próxima Revisão', type: 'date' },
        ],
      },
    ],
    relationships: [
      {
        id: 'rel_empresa_edificacao',
        name: 'Empresa possui Edificações',
        sourceTableId: 'tbl_empresas',
        sourceFieldId: 'fld_emp_id',
        targetTableId: 'tbl_edificacoes',
        targetFieldId: 'fld_edf_empresa_id',
        cardinality: '1:N',
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
      },
      {
        id: 'rel_edificacao_inspecao',
        name: 'Edificação possui Vistorias / Inspeções',
        sourceTableId: 'tbl_edificacoes',
        sourceFieldId: 'fld_edf_id',
        targetTableId: 'tbl_inspecoes',
        targetFieldId: 'fld_insp_edificacao_id',
        cardinality: '1:N',
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
      },
      {
        id: 'rel_inspecao_nc',
        name: 'Inspeção aponta Não Conformidades',
        sourceTableId: 'tbl_inspecoes',
        sourceFieldId: 'fld_insp_id',
        targetTableId: 'tbl_nao_conformidades',
        targetFieldId: 'fld_nc_inspecao_id',
        cardinality: '1:N',
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
      },
      {
        id: 'rel_edificacao_sistemas',
        name: 'Edificação possui Sistemas Preventivos',
        sourceTableId: 'tbl_edificacoes',
        sourceFieldId: 'fld_edf_id',
        targetTableId: 'tbl_sistemas_instalados',
        targetFieldId: 'fld_sis_edificacao_id',
        cardinality: '1:N',
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
      },
    ],
    layouts: [
      {
        id: 'lay_edificacoes_form',
        name: 'Cadastro de Edificação com Vistorias (Portal)',
        tableId: 'tbl_edificacoes',
        type: 'form',
        isDefault: true,
        components: [
          {
            id: 'c1',
            type: 'text',
            content: '### Ficha Cadastral da Edificação & Riscos Ocupacionais',
            position: { x: 0, y: 0, w: 12, h: 1 },
          },
          { id: 'c2', type: 'field-input', fieldId: 'fld_edf_nome', position: { x: 0, y: 1, w: 8, h: 1 } },
          { id: 'c3', type: 'field-input', fieldId: 'fld_edf_empresa_id', position: { x: 8, y: 1, w: 4, h: 1 } },
          { id: 'c4', type: 'field-input', fieldId: 'fld_edf_endereco', position: { x: 0, y: 2, w: 8, h: 1 } },
          { id: 'c5', type: 'field-input', fieldId: 'fld_edf_cidade', position: { x: 8, y: 2, w: 4, h: 1 } },
          { id: 'c6', type: 'field-input', fieldId: 'fld_edf_area', position: { x: 0, y: 3, w: 3, h: 1 } },
          { id: 'c7', type: 'field-input', fieldId: 'fld_edf_altura', position: { x: 3, y: 3, w: 3, h: 1 } },
          { id: 'c8', type: 'field-input', fieldId: 'fld_edf_pavimentos', position: { x: 6, y: 3, w: 3, h: 1 } },
          { id: 'c9', type: 'field-input', fieldId: 'fld_edf_grau_risco', position: { x: 9, y: 3, w: 3, h: 1 } },
          {
            id: 'c10',
            type: 'portal',
            label: 'Histórico de Inspeções Técnicas Vinculadas',
            relatedTableId: 'tbl_inspecoes',
            relatedRelationshipId: 'rel_edificacao_inspecao',
            portalColumns: ['fld_insp_data', 'fld_insp_inspetor', 'fld_insp_status', 'fld_insp_validade_alvara'],
            position: { x: 0, y: 4, w: 12, h: 3 },
          },
        ],
      },
    ],
    scripts: [
      {
        id: 'scr_alerta_reprovacao',
        name: 'Auto-Gerar Não Conformidade Crítica',
        description: 'Quando inspeção for Reprovada, exibe notificação e orienta cadastro imediato de anomalia.',
        trigger: 'OnRecordUpdate',
        tableId: 'tbl_inspecoes',
        actions: [
          {
            id: 'act_1',
            type: 'If',
            expression: "status_parecer == 'Reprovado'",
            subActions: [
              {
                id: 'act_sub_1',
                type: 'ShowDialog',
                message: 'Atenção: A vistoria foi REPROVADA. Notifique o Corpo de Bombeiros e registre as Não Conformidades impeditivas.',
              },
            ],
          },
        ],
      },
    ],
    reports: [
      {
        id: 'rep_laudo_tecnico',
        name: 'Laudo Técnico de Inspeção SCI',
        tableId: 'tbl_inspecoes',
        title: 'LAUDO TÉCNICO DE SEGURANÇA CONTRA INCÊNDIO & PÂNICO',
        subtitle: 'SYGMA ENGENHARIA — DIAGNÓSTICO DE CONFORMIDADE NORMATIVA',
        headerText: 'Sygma Database Studio AI · Vistoria Oficial de Edificações',
        footerText: 'Documento gerado eletronicamente em conformidade com as ITs do Corpo de Bombeiros.',
        includeDate: true,
        includePageNumbers: true,
        includeSignatureBlock: true,
        columns: [
          { fieldId: 'fld_insp_data', header: 'Data da Vistoria', width: '25%' },
          { fieldId: 'fld_insp_inspetor', header: 'Engenheiro Responsável', width: '35%' },
          { fieldId: 'fld_insp_status', header: 'Parecer Técnico', width: '20%' },
          { fieldId: 'fld_insp_validade_alvara', header: 'Validade AVCB', width: '20%' },
        ],
      },
      {
        id: 'rep_nao_conformidades',
        name: 'Relatório Executivo de Não Conformidades & Prazos',
        tableId: 'tbl_nao_conformidades',
        title: 'RELATÓRIO DE NÃO CONFORMIDADES E PLANO DE AÇÃO',
        subtitle: 'Pendências Críticas e Recomendações Corretivas',
        includeDate: true,
        includeSignatureBlock: true,
        columns: [
          { fieldId: 'fld_nc_sistema', header: 'Sistema', width: '25%' },
          { fieldId: 'fld_nc_local', header: 'Local', width: '20%' },
          { fieldId: 'fld_nc_gravidade', header: 'Gravidade', width: '15%' },
          { fieldId: 'fld_nc_situacao', header: 'Situação', width: '20%' },
          { fieldId: 'fld_nc_prazo', header: 'Prazo', width: '20%' },
        ],
      },
    ],
    dashboards: [
      {
        id: 'dsh_gerencial_sci',
        name: 'Painel Geral de Conformidade SCI',
        title: 'Painel Geral de Conformidade e Prevenção de Incêndio',
        description: 'Indicadores operacionais de vistorias, edificações cadastradas e gravidade de anomalias',
        widgets: [
          {
            id: 'w1',
            title: 'Total de Edificações',
            type: 'kpi-card',
            tableId: 'tbl_edificacoes',
            aggregate: 'COUNT',
            color: 'cyan',
            colSpan: 1,
          },
          {
            id: 'w2',
            title: 'Total de Vistorias Realizadas',
            type: 'kpi-card',
            tableId: 'tbl_inspecoes',
            aggregate: 'COUNT',
            color: 'emerald',
            colSpan: 1,
          },
          {
            id: 'w3',
            title: 'Não Conformidades Pendentes',
            type: 'kpi-card',
            tableId: 'tbl_nao_conformidades',
            aggregate: 'COUNT',
            filter: "situacao_correcao == 'Pendente'",
            color: 'rose',
            colSpan: 1,
          },
          {
            id: 'w4',
            title: 'Sistemas Preventivos Cadastrados',
            type: 'kpi-card',
            tableId: 'tbl_sistemas_instalados',
            aggregate: 'COUNT',
            color: 'amber',
            colSpan: 1,
          },
          {
            id: 'w5',
            title: 'Distribuição dos Pareceres de Vistoria',
            type: 'bar-chart',
            tableId: 'tbl_inspecoes',
            groupByFieldId: 'fld_insp_status',
            colSpan: 2,
          },
          {
            id: 'w6',
            title: 'Anomalias por Gravidade de Risco',
            type: 'pie-chart',
            tableId: 'tbl_nao_conformidades',
            groupByFieldId: 'fld_nc_gravidade',
            colSpan: 2,
          },
        ],
      },
    ],
    roles: [
      {
        id: 'role_admin',
        name: 'Engenheiro Chefe / Administrador',
        permissions: {
          canManageSchema: true,
          canExportData: true,
          tablePermissions: {
            tbl_empresas: { create: true, read: true, update: true, delete: true },
            tbl_edificacoes: { create: true, read: true, update: true, delete: true },
            tbl_inspecoes: { create: true, read: true, update: true, delete: true },
            tbl_nao_conformidades: { create: true, read: true, update: true, delete: true },
            tbl_sistemas_instalados: { create: true, read: true, update: true, delete: true },
          },
        },
      },
    ],
    settings: {
      theme: 'dark',
      language: 'pt-BR',
      enforceForeignKeys: true,
      autoAudit: true,
    },
  },
  initialData: {
    tbl_empresas: [
      {
        fld_emp_id: 'emp-001',
        fld_emp_razao: 'Condomínio Continental Tower',
        fld_emp_cnpj: '18.234.567/0001-90',
        fld_emp_contato: 'Carlos Mendonça',
        fld_emp_email: 'adm@continental.com.br',
        fld_emp_telefone: '(11) 3244-8800',
      },
      {
        fld_emp_id: 'emp-002',
        fld_emp_razao: 'Indústrias Metalúrgicas Vanguarda S/A',
        fld_emp_cnpj: '45.890.123/0001-44',
        fld_emp_contato: 'Fernanda Silveira',
        fld_emp_email: 'seguranca@vanguarda.ind.br',
        fld_emp_telefone: '(19) 3881-2299',
      },
      {
        fld_emp_id: 'emp-003',
        fld_emp_razao: 'Hospital Santa Helena Participações',
        fld_emp_cnpj: '03.712.940/0001-12',
        fld_emp_contato: 'Dr. Roberto Aguiar',
        fld_emp_email: 'diretoria@hospitalsantahelena.org',
        fld_emp_telefone: '(11) 5011-3000',
      },
    ],
    tbl_edificacoes: [
      {
        fld_edf_id: 'edf-001',
        fld_edf_empresa_id: 'emp-001',
        fld_edf_nome: 'Edifício Continental Corporate',
        fld_edf_endereco: 'Av. Paulista, 1850',
        fld_edf_cidade: 'São Paulo',
        fld_edf_area: 28500,
        fld_edf_altura: 88.5,
        fld_edf_pavimentos: 24,
        fld_edf_ocupacao: 'Comercial / Escritórios',
        fld_edf_grau_risco: 'Médio',
      },
      {
        fld_edf_id: 'edf-002',
        fld_edf_empresa_id: 'emp-002',
        fld_edf_nome: 'Galpão Industrial Módulo 01',
        fld_edf_endereco: 'Rodovia Anhanguera, km 104',
        fld_edf_cidade: 'Campinas',
        fld_edf_area: 14200,
        fld_edf_altura: 12.0,
        fld_edf_pavimentos: 2,
        fld_edf_ocupacao: 'Indústria / Logística',
        fld_edf_grau_risco: 'Alto',
      },
      {
        fld_edf_id: 'edf-003',
        fld_edf_empresa_id: 'emp-003',
        fld_edf_nome: 'Complexo Hospitalar Ala Norte',
        fld_edf_endereco: 'Rua Vergueiro, 2200',
        fld_edf_cidade: 'São Paulo',
        fld_edf_area: 32000,
        fld_edf_altura: 45.0,
        fld_edf_pavimentos: 11,
        fld_edf_ocupacao: 'Hospitalar / Saúde',
        fld_edf_grau_risco: 'Especial',
      },
    ],
    tbl_inspecoes: [
      {
        fld_insp_id: 'insp-101',
        fld_insp_edificacao_id: 'edf-001',
        fld_insp_data: '2026-03-12',
        fld_insp_inspetor: 'Eng. Ricardo Barros - CREA 506.124/SP',
        fld_insp_crea: '506.124/SP',
        fld_insp_status: 'Aprovado com Ressalvas',
        fld_insp_validade_alvara: '2027-03-12',
        fld_insp_obs: 'Vistoria anual para renovação de AVCB. Pressurização de escadas operando normalmente.',
      },
      {
        fld_insp_id: 'insp-102',
        fld_insp_edificacao_id: 'edf-002',
        fld_insp_data: '2026-03-18',
        fld_insp_inspetor: 'Eng. Beatriz Lins - CREA 480.990/SP',
        fld_insp_crea: '480.990/SP',
        fld_insp_status: 'Reprovado',
        fld_insp_validade_alvara: '2026-04-18',
        fld_insp_obs: 'Bomba de incêndio principal em pane mecânica e bicos de sprinkler obstruídos por pallets.',
      },
      {
        fld_insp_id: 'insp-103',
        fld_insp_edificacao_id: 'edf-003',
        fld_insp_data: '2026-03-24',
        fld_insp_inspetor: 'Eng. Ricardo Barros - CREA 506.124/SP',
        fld_insp_crea: '506.124/SP',
        fld_insp_status: 'Aprovado',
        fld_insp_validade_alvara: '2027-03-24',
        fld_insp_obs: 'Sistemas de detecção precoce de fumaça e geradores de emergência plenamente testados e certificados.',
      },
    ],
    tbl_nao_conformidades: [
      {
        fld_nc_id: 'nc-001',
        fld_nc_inspecao_id: 'insp-101',
        fld_nc_sistema: 'Iluminação de Emergência',
        fld_nc_local: 'Escada de Emergência - 14º Pavimento',
        fld_nc_descricao: 'Bloco autônomo com bateria descarregada, não acionando em teste manual.',
        fld_nc_gravidade: 'Média',
        fld_nc_prazo: '2026-04-15',
        fld_nc_situacao: 'Em Correção',
      },
      {
        fld_nc_id: 'nc-002',
        fld_nc_inspecao_id: 'insp-102',
        fld_nc_sistema: 'Sprinklers',
        fld_nc_local: 'Galpão Principal - Ala Sul',
        fld_nc_descricao: 'Empilhamento de mercadorias a menos de 50 cm dos bicos de chuveiros automáticos, violando NFPA 13.',
        fld_nc_gravidade: 'Crítica',
        fld_nc_prazo: '2026-03-30',
        fld_nc_situacao: 'Pendente',
      },
      {
        fld_nc_id: 'nc-003',
        fld_nc_inspecao_id: 'insp-102',
        fld_nc_sistema: 'Hidrantes & Mangotinhos',
        fld_nc_local: 'Casa de Bombas Subterrânea',
        fld_nc_descricao: 'Válvula de retenção travada e manômetro danificado sem aferição INMETRO.',
        fld_nc_gravidade: 'Grave',
        fld_nc_prazo: '2026-04-05',
        fld_nc_situacao: 'Pendente',
      },
    ],
    tbl_sistemas_instalados: [
      {
        fld_sis_id: 'sis-001',
        fld_sis_edificacao_id: 'edf-001',
        fld_sis_nome: 'Rede de Chuveiros Automáticos (Sprinklers)',
        fld_sis_tipo: 'Combate Automático a Água',
        fld_sis_qtd: 1200,
        fld_sis_marca: 'Viking / Tyco K80',
        fld_sis_status_op: 'Operacional',
        fld_sis_prox_revisao: '2026-09-12',
      },
      {
        fld_sis_id: 'sis-002',
        fld_sis_edificacao_id: 'edf-001',
        fld_sis_nome: 'Pressurização de Escadas de Segurança',
        fld_sis_tipo: 'Ventilação Mecânica & Fumaça',
        fld_sis_qtd: 2,
        fld_sis_marca: 'BerlinerLuft 15HP',
        fld_sis_status_op: 'Operacional',
        fld_sis_prox_revisao: '2026-08-01',
      },
      {
        fld_sis_id: 'sis-003',
        fld_sis_edificacao_id: 'edf-002',
        fld_sis_nome: 'Motobomba Principal de Incêndio',
        fld_sis_tipo: 'Hidráulica de Combate',
        fld_sis_qtd: 1,
        fld_sis_marca: 'Kapur / Cummins Diesel 120CV',
        fld_sis_status_op: 'Inoperante',
        fld_sis_prox_revisao: '2026-04-01',
      },
      {
        fld_sis_id: 'sis-004',
        fld_sis_edificacao_id: 'edf-003',
        fld_sis_nome: 'Central de Alarme Endereçável',
        fld_sis_tipo: 'Detecção Precoce & Alarme',
        fld_sis_qtd: 450,
        fld_sis_marca: 'Notifier / Honeywell NFS-320',
        fld_sis_status_op: 'Operacional',
        fld_sis_prox_revisao: '2026-07-20',
      },
    ],
  },
};

// 2. Gestão de Ativos & Manutenção Industrial
export const assetMaintenanceTemplate: TemplateDefinition = {
  id: 'template_asset_maintenance',
  name: 'Gestão de Ativos & Manutenção Preditiva',
  category: 'Manutenção & Engenharia',
  description: 'Controle de ordens de serviço, equipamentos, histórico de intervenções preventivas e estoques de peças.',
  icon: 'Wrench',
  schema: {
    application: {
      id: 'app_sygma_maint_2026',
      name: 'Gestão de Ativos & Manutenção Predial/Industrial',
      description: 'Plataforma para monitoramento de ativos, chamados técnicos e manutenções preventivas.',
      version: '1.0.0',
      author: 'SYGMA SMS / UNIVERSYGMA',
      createdAt: '2026-09-25T10:00:00Z',
      updatedAt: '2026-09-25T10:00:00Z',
      category: 'Manutenção',
      icon: 'Tool',
    },
    tables: [
      {
        id: 'tbl_ativos',
        name: 'ativos',
        singularLabel: 'Ativo / Equipamento',
        pluralLabel: 'Ativos',
        description: 'Máquinas, transformadores, compressores e geradores',
        primaryKeyFieldId: 'fld_atv_id',
        position: { x: 80, y: 100 },
        fields: [
          { id: 'fld_atv_id', name: 'id', label: 'Código do Ativo', type: 'uuid', primaryKey: true, isSystem: true },
          { id: 'fld_atv_tag', name: 'tag', label: 'TAG Identificador', type: 'text', validation: { required: true, unique: true } },
          { id: 'fld_atv_nome', name: 'nome_equipamento', label: 'Equipamento', type: 'text', validation: { required: true } },
          { id: 'fld_atv_setor', name: 'setor_localizacao', label: 'Setor / Fábrica', type: 'text' },
          { id: 'fld_atv_criticidade', name: 'criticidade', label: 'Criticidade', type: 'text', validation: { options: ['Alta (A)', 'Média (B)', 'Baixa (C)'] } },
          { id: 'fld_atv_status', name: 'status_operacional', label: 'Estado', type: 'text', validation: { options: ['Em Operação', 'Parada Programada', 'Em Manutenção', 'Sucata'] } },
        ],
      },
      {
        id: 'tbl_ordens_servico',
        name: 'ordens_servico',
        singularLabel: 'Ordem de Serviço',
        pluralLabel: 'Ordens de Serviço',
        description: 'Intervenções corretivas e preventivas',
        primaryKeyFieldId: 'fld_os_id',
        position: { x: 500, y: 100 },
        fields: [
          { id: 'fld_os_id', name: 'id', label: 'ID O.S.', type: 'uuid', primaryKey: true, isSystem: true },
          { id: 'fld_os_ativo_id', name: 'ativo_id', label: 'Ativo', type: 'uuid', validation: { required: true } },
          { id: 'fld_os_numero', name: 'numero_os', label: 'Nº OS', type: 'text', validation: { required: true } },
          { id: 'fld_os_tipo', name: 'tipo_manutencao', label: 'Tipo', type: 'text', validation: { options: ['Preventiva', 'Corretiva', 'Preditiva', 'Melhoria'] } },
          { id: 'fld_os_data', name: 'data_abertura', label: 'Data Abertura', type: 'date', validation: { required: true } },
          { id: 'fld_os_tecnico', name: 'tecnico_responsavel', label: 'Técnico', type: 'text' },
          { id: 'fld_os_custo', name: 'custo_total', label: 'Custo Total (R$)', type: 'currency' },
          { id: 'fld_os_status', name: 'status', label: 'Status OS', type: 'text', validation: { options: ['Aberta', 'Em Execução', 'Aguardando Peça', 'Concluída'] } },
        ],
      },
    ],
    relationships: [
      {
        id: 'rel_ativo_os',
        name: 'Ativo possui Ordens de Serviço',
        sourceTableId: 'tbl_ativos',
        sourceFieldId: 'fld_atv_id',
        targetTableId: 'tbl_ordens_servico',
        targetFieldId: 'fld_os_ativo_id',
        cardinality: '1:N',
        onDelete: 'CASCADE',
        onUpdate: 'CASCADE',
      },
    ],
    layouts: [],
    scripts: [],
    reports: [
      {
        id: 'rep_os_mensal',
        name: 'Relatório Mensal de Manutenção',
        tableId: 'tbl_ordens_servico',
        title: 'RELATÓRIO GERENCIAL DE ORDENS DE SERVIÇO',
        subtitle: 'Apuração de Custos e Disponibilidade Operacional',
        columns: [
          { fieldId: 'fld_os_numero', header: 'Nº OS', width: '20%' },
          { fieldId: 'fld_os_tipo', header: 'Tipo', width: '25%' },
          { fieldId: 'fld_os_tecnico', header: 'Técnico', width: '30%' },
          { fieldId: 'fld_os_status', header: 'Status', width: '25%' },
        ],
      },
    ],
    dashboards: [
      {
        id: 'dsh_manutencao',
        name: 'Dashboard Operacional Manutenção',
        title: 'Controle de MTBF e Execução de OS',
        widgets: [
          { id: 'wm1', title: 'Total de Ativos', type: 'kpi-card', tableId: 'tbl_ativos', aggregate: 'COUNT', colSpan: 1 },
          { id: 'wm2', title: 'OS Abertas', type: 'kpi-card', tableId: 'tbl_ordens_servico', filter: "status != 'Concluída'", aggregate: 'COUNT', colSpan: 1 },
          { id: 'wm3', title: 'OS por Tipo', type: 'pie-chart', tableId: 'tbl_ordens_servico', groupByFieldId: 'fld_os_tipo', colSpan: 2 },
        ],
      },
    ],
    roles: [],
    settings: { theme: 'dark', language: 'pt-BR', enforceForeignKeys: true, autoAudit: true },
  },
  initialData: {
    tbl_ativos: [
      { fld_atv_id: 'atv-1', fld_atv_tag: 'COMP-01', fld_atv_nome: 'Compressor Parafuso Atlas Copco 50HP', fld_atv_setor: 'Utilidades', fld_atv_criticidade: 'Alta (A)', fld_atv_status: 'Em Operação' },
      { fld_atv_id: 'atv-2', fld_atv_tag: 'GER-02', fld_atv_nome: 'Grupo Gerador Stemac 500kVA Diesel', fld_atv_setor: 'Subestação', fld_atv_criticidade: 'Alta (A)', fld_atv_status: 'Em Operação' },
      { fld_atv_id: 'atv-3', fld_atv_tag: 'CLIM-08', fld_atv_nome: 'Chiller Trane Centrifugo 200TR', fld_atv_setor: 'Ar Condicionado Central', fld_atv_criticidade: 'Média (B)', fld_atv_status: 'Em Manutenção' },
    ],
    tbl_ordens_servico: [
      { fld_os_id: 'os-1', fld_os_ativo_id: 'atv-1', fld_os_numero: 'OS-2026-081', fld_os_tipo: 'Preventiva', fld_os_data: '2026-03-10', fld_os_tecnico: 'Marcos Vinicius', fld_os_custo: 1850, fld_os_status: 'Concluída' },
      { fld_os_id: 'os-2', fld_os_ativo_id: 'atv-3', fld_os_numero: 'OS-2026-094', fld_os_tipo: 'Corretiva', fld_os_data: '2026-03-22', fld_os_tecnico: 'Gabriel Soares', fld_os_custo: 4200, fld_os_status: 'Em Execução' },
    ],
  },
};

export const ALL_TEMPLATES: TemplateDefinition[] = [
  fireSafetyTemplate,
  assetMaintenanceTemplate,
];
